apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: davinci-initdb
  name: davinci-initdb
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: alicloud-nas
status: {}
