apiVersion: v1
kind: Service
metadata:
  name: feb-usr
  labels:
    app: feb-usr
spec:
  ports:
    - port: 80
      nodePort: 30204
      targetPort: user-port
  selector:
    app: feb-usr
    tier: backend
  type: NodePort
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: feb-usr
  labels:
    app: feb-usr
spec:
  selector:
    matchLabels:
      app: feb-usr
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: feb-usr
        tier: backend
    spec:
      containers:
      - image: 192.168.0.205:5000/cloud-user-center
        name: user-center
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: feb-mysql
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: febs-secret
              key: mysql-password
        - name: DB_USERNSME
          valueFrom:
            secretKeyRef:
              name: febs-secret
              key: mysql-username
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: febs-configmap
              key: mysql-db
        ports:
        - containerPort: 8204
          name: user-port