apiVersion: v1
kind: Service
metadata:
  name: feb-config
  labels:
    app: feb-config
spec:
  ports:
    - port: 80
      targetPort: config-port
  selector:
    app: feb-config
    tier: backend
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: feb-config
  labels:
    app: feb-config
spec:
  selector:
    matchLabels:
      app: feb-config
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: feb-config
        tier: backend
    spec:
      containers:
      - image: 192.168.0.205:5000/cloud-config
        name: feb-config
        imagePullPolicy: Always
        ports:
        - containerPort: 8202
          name: config-port
