apiVersion: v1
kind: Service
metadata:
  name: feb-zuul
  labels:
    app: feb-zuul
spec:
  ports:
    - port: 80
      nodePort: 30203
      targetPort: zull-port
  selector:
    app: feb-zuul
    tier: backend
  type: NodePort
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: feb-zuul
  labels:
    app: feb-zuul
spec:
  selector:
    matchLabels:
      app: feb-zuul
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: feb-zuul
        tier: backend
    spec:
      containers:
      - image: 192.168.0.205:5000/cloud-zuul
        name: zuul
        imagePullPolicy: Always
        ports:
        - containerPort: 8203
          name: zull-port