apiVersion: v1
kind: Service
metadata:
  name: feb-eureka
  labels:
    app: feb-eureka
spec:
  ports:
    - port: 80
      nodePort: 30201
      targetPort: eureka-port
  selector:
    app: feb-eureka
    tier: backend
  type: NodePort
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: feb-eureka
  labels:
    app: feb-eureka
spec:
  selector:
    matchLabels:
      app: feb-eureka
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: feb-eureka
        tier: backend
    spec:
      containers:
      - image: 192.168.0.205:5000/cloud-eureka
        name: eureka
        imagePullPolicy: Always
        ports:
        - containerPort: 8201
          name: eureka-port
